version: '3'
services:
  r-ver-4.0.0-ubuntu18.04:
    image: rocker/r-ver:4.0.0-ubuntu18.04
    build:
      context: ..
      dockerfile: dockerfiles/r-ver_4.0.0-ubuntu18.04.Dockerfile
  rstudio-4.0.0-ubuntu18.04:
    image: rocker/rstudio:4.0.0-ubuntu18.04
    depends_on:
    - r-ver-4.0.0-ubuntu18.04
    build:
      context: ..
      dockerfile: dockerfiles/rstudio_4.0.0-ubuntu18.04.Dockerfile
  tidyverse-4.0.0-ubuntu18.04:
    image: rocker/tidyverse:4.0.0-ubuntu18.04
    depends_on:
    - rstudio-4.0.0-ubuntu18.04
    build:
      context: ..
      dockerfile: dockerfiles/tidyverse_4.0.0-ubuntu18.04.Dockerfile
  verse-4.0.0-ubuntu18.04:
    image: rocker/verse:4.0.0-ubuntu18.04
    depends_on:
    - tidyverse-4.0.0-ubuntu18.04
    build:
      context: ..
      dockerfile: dockerfiles/verse_4.0.0-ubuntu18.04.Dockerfile
