version: '3'
services:
  rstudio-latest-daily:
    image: rocker/rstudio:latest-daily
    build:
      context: ..
      dockerfile: dockerfiles/rstudio_latest-daily.Dockerfile
  tidyverse-latest-daily:
    image: rocker/tidyverse:latest-daily
    depends_on:
    - rstudio-latest-daily
    build:
      context: ..
      dockerfile: dockerfiles/tidyverse_latest-daily.Dockerfile
  verse-latest-daily:
    image: rocker/verse:latest-daily
    depends_on:
    - tidyverse-latest-daily
    build:
      context: ..
      dockerfile: dockerfiles/verse_latest-daily.Dockerfile
