version: '3'
services:
  r-ver-devel-cuda11.1:
    image: rocker/r-ver:devel-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/r-ver_devel-cuda11.1.Dockerfile
  ml-devel-cuda11.1:
    image: rocker/ml:devel-cuda11.1
    depends_on:
    - r-ver-devel-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/ml_devel-cuda11.1.Dockerfile
  ml-verse-devel-cuda11.1:
    image: rocker/ml-verse:devel-cuda11.1
    depends_on:
    - ml-devel-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/ml-verse_devel-cuda11.1.Dockerfile
