version: '3'
services:
  r-ver-4.0.5-cuda11.1:
    image: rocker/r-ver:4.0.5-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/r-ver_4.0.5-cuda11.1.Dockerfile
  ml-4.0.5-cuda11.1:
    image: rocker/ml:4.0.5-cuda11.1
    depends_on:
    - r-ver-4.0.5-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/ml_4.0.5-cuda11.1.Dockerfile
  ml-verse-4.0.5-cuda11.1:
    image: rocker/ml-verse:4.0.5-cuda11.1
    depends_on:
    - ml-4.0.5-cuda11.1
    build:
      context: ..
      dockerfile: dockerfiles/ml-verse_4.0.5-cuda11.1.Dockerfile
