name: Build & Push Core images

on:
  push:
    branches:
      - "master"
    paths:
      - "scripts/**"
      - "dockerfiles/*_devel.Dockerfile"
  workflow_run:
    workflows:
      - "Create new release"
    branches:
      - "master"
    types:
      - completed
  workflow_dispatch:

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-json
        run: |
          JSON=build/matrix/latest.json
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            JSON=build/matrix/all.json
          fi
          echo ::set-output name=json::${JSON}
          echo ${JSON}
      - id: set-matrix
        run: |
          CONTENT=$(jq -r 'tostring' ${{ steps.set-json.outputs.json }})
          echo ::set-output name=matrix::${CONTENT}
          echo ${CONTENT}

  build:
    needs: generate_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push Docker images
        run: |
          BAKE_JSON=bakefiles/${{ matrix.r_version }}.docker-bake.json BAKE_OPTION=--load\ --push make bake-json-all
      - name: Inspect built image
        run: |
          IMAGELIST_NAME=${{ matrix.r_version }}.tsv make inspect-image-all
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: tmp
          path: tmp

  publish_reports:
    if: always()
    needs: build
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Checkout wiki
        uses: actions/checkout@v2
        with:
          repository: "${{ github.repository }}.wiki"
          path: reports
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: tmp
          path: tmp
      - name: Generate reports and update wiki home
        run: |
          make report-all
          make wiki-home
      - name: Update wiki
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated update
          repository: reports
