name: Build & Push R devel images and RStudio daily build images

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        composefile: [core-devel.yml, core-latest-daily.yml]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker images
        run: docker-compose -f compose/${{ matrix.composefile }} build
      - name: Push Docker images
        run: docker-compose -f compose/${{ matrix.composefile }} push
