name: Build & Push Core devel images

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the tagged Docker image
        run: docker-compose -f compose/core-devel.yml build
      - name: Push the tagged Docker image
        run: docker-compose  -f compose/core-devel.yml push
