on:
  push:
    paths: ['scripts/experimental/install_dev_osgeo.sh']


jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: rocker/r-ver
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: bash scripts/experimental/install_dev_osgeo.sh
  